create database blogdb;
use blogdb;

Create Table blog_posts(
    id bigint(20) AUTO_INCREMENT PRIMARY KEY,
    post_title varchar(255),
    post_content LONGTEXT
);

CREATE TABLE users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO blog_posts (post_title, post_content)
VALUES ('Click here to see post content', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. In tellus integer feugiat scelerisque. Tincidunt lobortis feugiat vivamus at augue eget. Est pellentesque elit ullamcorper dignissim. In fermentum posuere urna nec tincidunt praesent semper feugiat nibh. Quam adipiscing vitae proin sagittis. Augue lacus viverra vitae congue eu consequat ac felis donec. Dolor magna eget est lorem ipsum dolor sit amet. Fusce ut placerat orci nulla pellentesque. Ornare arcu dui vivamus arcu felis bibendum. Amet facilisis magna etiam tempor orci. Tristique et egestas quis ipsum. Ut pharetra sit amet aliquam id diam maecenas ultricies. Et sollicitudin ac orci phasellus egestas tellus. Molestie nunc non blandit massa enim nec. Tortor at auctor urna nunc id cursus metus.
Semper auctor neque vitae tempus quam. Amet purus gravida quis blandit turpis cursus in hac. Sed vulputate odio ut enim blandit volutpat. Ac tortor vitae purus faucibus ornare suspendisse sed. Lectus sit amet est placerat in egestas erat imperdiet sed. Dui vivamus arcu felis bibendum ut tristique. Netus et malesuada fames ac turpis. Odio pellentesque diam volutpat commodo sed egestas egestas. Enim nec dui nunc mattis enim ut tellus elementum. Eget nunc scelerisque viverra mauris in aliquam sem. Commodo ullamcorper a lacus vestibulum sed arcu non odio. Luctus accumsan tortor posuere ac ut consequat semper viverra nam. Elit duis tristique sollicitudin nibh sit amet commodo nulla.
Blandit turpis cursus in hac. Sem nulla pharetra diam sit');

INSERT INTO blog_posts (post_title, post_content)
VALUES ('test post', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. In tellus integer feugiat scelerisque. Tincidunt lobortis feugiat vivamus at augue eget. Est pellentesque elit ullamcorper dignissim. In fermentum posuere urna nec tincidunt praesent semper feugiat nibh. Quam adipiscing vitae proin sagittis. Augue lacus viverra vitae congue eu consequat ac felis donec. Dolor magna eget est lorem ipsum dolor sit amet. Fusce ut placerat orci nulla pellentesque. Ornare arcu dui vivamus arcu felis bibendum. Amet facilisis magna etiam tempor orci. Tristique et egestas quis ipsum. Ut pharetra sit amet aliquam id diam maecenas ultricies. Et sollicitudin ac orci phasellus egestas tellus. Molestie nunc non blandit massa enim nec. Tortor at auctor urna nunc id cursus metus.
Semper auctor neque vitae tempus quam. Amet purus gravida quis blandit turpis cursus in hac. Sed vulputate odio ut enim blandit volutpat. Ac tortor vitae purus faucibus ornare suspendisse sed. Lectus sit amet est placerat in egestas erat imperdiet sed. Dui vivamus arcu felis bibendum ut tristique. Netus et malesuada fames ac turpis. Odio pellentesque diam volutpat commodo sed egestas egestas. Enim nec dui nunc mattis enim ut tellus elementum. Eget nunc scelerisque viverra mauris in aliquam sem. Commodo ullamcorper a lacus vestibulum sed arcu non odio. Luctus accumsan tortor posuere ac ut consequat semper viverra nam. Elit duis tristique sollicitudin nibh sit amet commodo nulla.
Blandit turpis cursus in hac. Sem nulla pharetra diam sit amet nisl suscipit adipiscing bibendum. Lectus quam id leo in vitae turpis massa. Suspendisse sed nisi lacus sed viverra tellus in hac. Neque vitae tempus quam pellentesque nec nam aliquam sem et. In fermentum et sollicitudin ac orci phasellus egestas tellus rutrum. Venenatis urna cursus eget nunc scelerisque viverra mauris in aliquam. Nunc eget lorem dolor sed viverra ipsum nunc aliquet. Ut ornare lectus sit amet est. In cursus turpis massa tincidunt. Bibendum at varius vel pharetra vel turpis nunc eget lorem. Tellus at urna condimentum mattis pellentesque id.
Consectetur adipiscing elit ut aliquam purus sit amet luctus. Mauris a diam maecenas sed enim ut sem. Nisl pretium fusce id velit ut tortor pretium viverra suspendisse. Elementum sagittis vitae et leo duis ut diam quam nulla. Vestibulum mattis ullamcorper velit sed ullamcorper morbi tincidunt ornare massa. Semper feugiat nibh sed pulvinar proin. Ipsum dolor sit amet consectetur adipiscing elit ut aliquam. Eu turpis egestas pretium aenean pharetra magna. Auctor augue mauris augue neque gravida in. Tincidunt lobortis feugiat vivamus at augue. Dolor sed viverra ipsum nunc aliquet bibendum enim facilisis gravida. Turpis cursus in hac habitasse platea. Nisl rhoncus mattis rhoncus urna.
Dui faucibus in ornare quam. Est lorem ipsum dolor sit amet. Amet porttitor eget dolor morbi non arcu risus quis. Platea dictumst quisque sagittis purus sit amet volutpat. Tincidunt augue interdum velit euismod. Eros in cursus turpis massa. Ut faucibus pulvinar elementum integer enim. Tellus elementum sagittis vitae et leo duis ut diam. Adipiscing at in tellus integer feugiat scelerisque varius. In nibh mauris cursus mattis. Fames ac turpis egestas maecenas pharetra. Cras tincidunt lobortis feugiat vivamus at augue eget arcu dictum. Velit ut tortor pretium viverra suspendisse. Aliquam vestibulum morbi blandit cursus risus at.');

INSERT INTO blog_posts (post_title, post_content)
VALUES ('Post 2', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. In tellus integer feugiat scelerisque. Tincidunt lobortis feugiat vivamus at augue eget. Est pellentesque elit ullamcorper dignissim. In fermentum posuere urna nec tincidunt praesent semper feugiat nibh. Quam adipiscing vitae proin sagittis. Augue lacus viverra vitae congue eu consequat ac felis donec. Dolor magna eget est lorem ipsum dolor sit amet. Fusce ut placerat orci nulla pellentesque. Ornare arcu dui vivamus arcu felis bibendum. Amet facilisis magna etiam tempor orci. Tristique et egestas quis ipsum. Ut pharetra sit amet aliquam id diam maecenas ultricies. Et sollicitudin ac orci phasellus egestas tellus. Molestie nunc non blandit massa enim nec. Tortor at auctor urna nunc id cursus metus.
Semper auctor neque vitae tempus quam. Amet purus gravida quis blandit turpis cursus in hac. Sed vulputate odio ut enim blandit volutpat. Ac tortor vitae purus faucibus ornare suspendisse sed. Lectus sit amet est placerat in egestas erat imperdiet sed. Dui vivamus arcu felis bibendum ut tristique. Netus et malesuada fames ac turpis. Odio pellentesque diam volutpat commodo sed egestas egestas. Enim nec dui nunc mattis enim ut tellus elementum. Eget nunc scelerisque viverra mauris in aliquam sem. Commodo ullamcorper a lacus vestibulum sed arcu non odio. Luctus accumsan tortor posuere ac ut consequat semper viverra nam. Elit duis tristique sollicitudin nibh sit amet commodo nulla.
Blandit turpis cursus in hac. Sem nulla pharetra diam sit amet nisl suscipit adipiscing bibendum. Lectus quam id leo in vitae turpis massa. Suspendisse sed nisi lacus sed viverra tellus in hac. Neque vitae tempus quam pellentesque nec nam aliquam sem et. In fermentum et sollicitudin ac orci phasellus egestas tellus rutrum. Venenatis urna cursus eget nunc scelerisque viverra mauris in aliquam. Nunc eget lorem dolor sed viverra ipsum nunc aliquet. Ut ornare lectus sit amet est. In cursus turpis massa tincidunt. Bibendum at varius vel pharetra vel turpis nunc eget lorem. Tellus at urna condimentum mattis pellentesque id.
Consectetur adipiscing elit ut aliquam purus sit amet luctus. Mauris a diam maecenas sed enim ut sem. Nisl pretium fusce id velit ut tortor pretium viverra suspendisse. Elementum sagittis vitae et leo duis ut diam quam nulla. Vestibulum mattis ullamcorper velit sed ullamcorper morbi tincidunt ornare massa. Semper feugiat nibh sed pulvinar proin. Ipsum dolor sit amet consectetur adipiscing elit ut aliquam. Eu turpis egestas pretium aenean pharetra magna. Auctor augue mauris augue neque gravida in. Tincidunt lobortis feugiat vivamus at augue. Dolor sed viverra ipsum nunc aliquet bibendum enim facilisis gravida. Turpis cursus in hac habitasse platea. Nisl rhoncus mattis rhoncus urna.
Dui faucibus in ornare quam. Est lorem ipsum dolor sit amet. Amet porttitor eget dolor morbi non arcu risus quis. Platea dictumst quisque sagittis purus sit amet volutpat. Tincidunt augue interdum velit euismod. Eros in cursus turpis massa. Ut faucibus pulvinar elementum integer enim. Tellus elementum sagittis vitae et leo duis ut diam. Adipiscing at in tellus integer feugiat scelerisque varius. In nibh mauris cursus mattis. Fames ac turpis egestas maecenas pharetra. Cras tincidunt lobortis feugiat vivamus at augue eget arcu dictum. Velit ut tortor pretium viverra suspendisse. Aliquam vestibulum morbi blandit cursus risus at.');

INSERT INTO users (username, password, created_at)
VALUES ('admin', '$2y$10$73gitjZ1/BpZos5kAW.VlO.Yfk5AHxztiCyxE9a1Cz8wru6a5G6cy', CURRENT_TIMESTAMP);
